CREATE TABLE IF NOT EXISTS estoque_itens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
    material_code VARCHAR(80) NOT NULL,
    variant VARCHAR(40) NOT NULL DEFAULT 'PADRAO',
    kind VARCHAR(20) NOT NULL,
    length_mm INTEGER NULL,
    quantity NUMERIC(14,3) NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'DISPONIVEL',
    source_item_id INTEGER NULL REFERENCES estoque_itens(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_estoque_item_qty_nonnegative CHECK (quantity >= 0),
    CONSTRAINT ck_estoque_item_length_positive CHECK (length_mm IS NULL OR length_mm > 0)
);
CREATE INDEX IF NOT EXISTS ix_estoque_itens_company_material ON estoque_itens(company_id, material_code);
CREATE INDEX IF NOT EXISTS ix_estoque_itens_disponivel ON estoque_itens(company_id, status);

CREATE TABLE IF NOT EXISTS estoque_movimentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES estoque_itens(id) ON DELETE RESTRICT,
    movement_type VARCHAR(30) NOT NULL,
    quantity NUMERIC(14,3) NOT NULL,
    reference VARCHAR(120),
    note VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_estoque_mov_company_item ON estoque_movimentos(company_id, item_id, created_at);
