CREATE TABLE IF NOT EXISTS estoque_reservas (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 company_id INTEGER NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
 reference VARCHAR(120) NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'ATIVA',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_reservas_company_status ON estoque_reservas(company_id,status);
CREATE TABLE IF NOT EXISTS estoque_reserva_itens (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 reservation_id INTEGER NOT NULL REFERENCES estoque_reservas(id) ON DELETE CASCADE,
 item_id INTEGER NOT NULL REFERENCES estoque_itens(id) ON DELETE RESTRICT,
 quantity NUMERIC(14,3) NOT NULL,
 CONSTRAINT uq_reserva_item UNIQUE(reservation_id,item_id),
 CONSTRAINT ck_reserva_qty_positive CHECK(quantity>0)
);
CREATE INDEX IF NOT EXISTS ix_reserva_itens_item ON estoque_reserva_itens(item_id);
